//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.

using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows;

namespace Expression.Blend.SampleData.SetshowInfo
{
// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SetshowInfo { }
#else

	public class SetshowInfo : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public SetshowInfo()
		{
			try
			{
				Uri resourceUri = new Uri("/SABA_CH;component/SampleData/SetshowInfo/SetshowInfo.xaml", UriKind.Relative);
				if (Application.GetResourceStream(resourceUri) != null)
				{
					Application.LoadComponent(this, resourceUri);
				}
			}
			catch (Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private double _OBIS = 0;

		public double OBIS
		{
			get
			{
				return this._OBIS;
			}

			set
			{
				if (this._OBIS != value)
				{
					this._OBIS = value;
					this.OnPropertyChanged("OBIS");
				}
			}
		}

		private string _شرح__فارسي = string.Empty;

		public string شرح__فارسي
		{
			get
			{
				return this._شرح__فارسي;
			}

			set
			{
				if (this._شرح__فارسي != value)
				{
					this._شرح__فارسي = value;
					this.OnPropertyChanged("شرح__فارسي");
				}
			}
		}

		private string _شرح__انگليسي = string.Empty;

		public string شرح__انگليسي
		{
			get
			{
				return this._شرح__انگليسي;
			}

			set
			{
				if (this._شرح__انگليسي != value)
				{
					this._شرح__انگليسي = value;
					this.OnPropertyChanged("شرح__انگليسي");
				}
			}
		}
	}

	public class ItemCollection : ObservableCollection<Item>
	{ 
	}
#endif
}
