//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.

using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows;

namespace Expression.Blend.SampleData.MainWindow
{
// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class MainWindow { }
#else

	public class MainWindow : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public MainWindow()
		{
			try
			{
				Uri resourceUri = new Uri("/SABA_CH;component/SampleData/MainWindow/MainWindow.xaml", UriKind.Relative);
				if (Application.GetResourceStream(resourceUri) != null)
				{
					Application.LoadComponent(this, resourceUri);
				}
			}
			catch (Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class ItemCollection : ObservableCollection<Item>
	{ 
	}

	public class Item : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private double _شماره__کنتور = 0;

		public double شماره__کنتور
		{
			get
			{
				return this._شماره__کنتور;
			}

			set
			{
				if (this._شماره__کنتور != value)
				{
					this._شماره__کنتور = value;
					this.OnPropertyChanged("شماره__کنتور");
				}
			}
		}

		private bool _انتخاب = false;

		public bool انتخاب
		{
			get
			{
				return this._انتخاب;
			}

			set
			{
				if (this._انتخاب != value)
				{
					this._انتخاب = value;
					this.OnPropertyChanged("انتخاب");
				}
			}
		}
	}
#endif
}
