//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.

using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows;

namespace Expression.Blend.SampleData.MoshakhasatKontor
{
// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class MoshakhasatKontor { }
#else

	public class MoshakhasatKontor : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public MoshakhasatKontor()
		{
			try
			{
				Uri resourceUri = new Uri("/SABA_CH;component/SampleData/MoshakhasatKontor/MoshakhasatKontor.xaml", UriKind.Relative);
				if (Application.GetResourceStream(resourceUri) != null)
				{
					Application.LoadComponent(this, resourceUri);
				}
			}
			catch (Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private double _مقدار = 0;

		public double مقدار
		{
			get
			{
				return this._مقدار;
			}

			set
			{
				if (this._مقدار != value)
				{
					this._مقدار = value;
					this.OnPropertyChanged("مقدار");
				}
			}
		}

		private string _اطلاعات = string.Empty;

		public string اطلاعات
		{
			get
			{
				return this._اطلاعات;
			}

			set
			{
				if (this._اطلاعات != value)
				{
					this._اطلاعات = value;
					this.OnPropertyChanged("اطلاعات");
				}
			}
		}

		private string _واحد = string.Empty;

		public string واحد
		{
			get
			{
				return this._واحد;
			}

			set
			{
				if (this._واحد != value)
				{
					this._واحد = value;
					this.OnPropertyChanged("واحد");
				}
			}
		}
	}

	public class ItemCollection : ObservableCollection<Item>
	{ 
	}
#endif
}
