//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.

using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows;

namespace Expression.Blend.SampleData.PublicRoydad
{
// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class PublicRoydad { }
#else

	public class PublicRoydad : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public PublicRoydad()
		{
			try
			{
				Uri resourceUri = new Uri("/SABA_CH;component/SampleData/PublicRoydad/PublicRoydad.xaml", UriKind.Relative);
				if (Application.GetResourceStream(resourceUri) != null)
				{
					Application.LoadComponent(this, resourceUri);
				}
			}
			catch (Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private string _کد__رویداد = string.Empty;

		public string کد__رویداد
		{
			get
			{
				return this._کد__رویداد;
			}

			set
			{
				if (this._کد__رویداد != value)
				{
					this._کد__رویداد = value;
					this.OnPropertyChanged("کد__رویداد");
				}
			}
		}

		private string _تاریخ__رویداد = string.Empty;

		public string تاریخ__رویداد
		{
			get
			{
				return this._تاریخ__رویداد;
			}

			set
			{
				if (this._تاریخ__رویداد != value)
				{
					this._تاریخ__رویداد = value;
					this.OnPropertyChanged("تاریخ__رویداد");
				}
			}
		}

		private string _شرح__رویداد = string.Empty;

		public string شرح__رویداد
		{
			get
			{
				return this._شرح__رویداد;
			}

			set
			{
				if (this._شرح__رویداد != value)
				{
					this._شرح__رویداد = value;
					this.OnPropertyChanged("شرح__رویداد");
				}
			}
		}

		private string _عامل__رویداد = string.Empty;

		public string عامل__رویداد
		{
			get
			{
				return this._عامل__رویداد;
			}

			set
			{
				if (this._عامل__رویداد != value)
				{
					this._عامل__رویداد = value;
					this.OnPropertyChanged("عامل__رویداد");
				}
			}
		}
	}

	public class ItemCollection : ObservableCollection<Item>
	{ 
	}
#endif
}
