//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.

using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows;

namespace Expression.Blend.SampleData.TestShowInfo2
{
// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class TestShowInfo2 { }
#else

	public class TestShowInfo2 : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public TestShowInfo2()
		{
			try
			{
				Uri resourceUri = new Uri("/SABA_CH;component/SampleData/TestShowInfo2/TestShowInfo2.xaml", UriKind.Relative);
				if (Application.GetResourceStream(resourceUri) != null)
				{
					Application.LoadComponent(this, resourceUri);
				}
			}
			catch (Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private string _اطلاعات = string.Empty;

		public string اطلاعات
		{
			get
			{
				return this._اطلاعات;
			}

			set
			{
				if (this._اطلاعات != value)
				{
					this._اطلاعات = value;
					this.OnPropertyChanged("اطلاعات");
				}
			}
		}

		private bool _انتخاب = false;

		public bool انتخاب
		{
			get
			{
				return this._انتخاب;
			}

			set
			{
				if (this._انتخاب != value)
				{
					this._انتخاب = value;
					this.OnPropertyChanged("انتخاب");
				}
			}
		}
	}

	public class ItemCollection : ObservableCollection<Item>
	{ 
	}
#endif
}
