//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.

using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows;

namespace Expression.Blend.SampleData.UseElec
{
// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class UseElec { }
#else

	public class UseElec : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public UseElec()
		{
			try
			{
				Uri resourceUri = new Uri("/SABA_CH;component/SampleData/UseElec/UseElec.xaml", UriKind.Relative);
				if (Application.GetResourceStream(resourceUri) != null)
				{
					Application.LoadComponent(this, resourceUri);
				}
			}
			catch (Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class ItemCollection : ObservableCollection<Item>
	{ 
	}

	public class Item : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private string _انرژی__اکتیو = string.Empty;

		public string انرژی__اکتیو
		{
			get
			{
				return this._انرژی__اکتیو;
			}

			set
			{
				if (this._انرژی__اکتیو != value)
				{
					this._انرژی__اکتیو = value;
					this.OnPropertyChanged("انرژی__اکتیو");
				}
			}
		}

		private double _مقدار = 0;

		public double مقدار
		{
			get
			{
				return this._مقدار;
			}

			set
			{
				if (this._مقدار != value)
				{
					this._مقدار = value;
					this.OnPropertyChanged("مقدار");
				}
			}
		}
	}
#endif
}
