//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABA_CH.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualCredit
    {
        public decimal Id { get; set; }
        public string WaterSubscriberNumber { get; set; }
        public string StartAnnualDate { get; set; }
        public string ChangeDate { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<decimal> Credit { get; set; }
    }
}
