//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABA_CH.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.CardToMeters = new HashSet<CardToMeter>();
        }
    
        public decimal CardID { get; set; }
        public string CardNumber { get; set; }
    
        public virtual ICollection<CardToMeter> CardToMeters { get; set; }
    }
}
