//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABA_CH.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catchment
    {
        public Catchment()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public decimal CatchmentID { get; set; }
        public string CatchmentName { get; set; }
        public string CatchmentCode { get; set; }
        public string ProvinceID { get; set; }
    
        public virtual ICollection<Location> Locations { get; set; }
    }
}
