//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABA_CH.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public decimal CityID { get; set; }
        public string CityCode { get; set; }
        public string CityName { get; set; }
        public Nullable<decimal> CountryID { get; set; }
        public Nullable<decimal> ProvinceID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Province Province { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}
