//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABA_CH.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Cities = new HashSet<City>();
            this.Provinces = new HashSet<Province>();
        }
    
        public decimal CountryID { get; set; }
        public string CountrtCode { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<Province> Provinces { get; set; }
    }
}
