//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABA_CH.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceType
    {
        public DeviceType()
        {
            this.DeviceModels = new HashSet<DeviceModel>();
            this.OBISValueHeaders = new HashSet<OBISValueHeader>();
        }
    
        public decimal DeviceTypeID { get; set; }
        public string DeviceName { get; set; }
    
        public virtual ICollection<DeviceModel> DeviceModels { get; set; }
        public virtual ICollection<OBISValueHeader> OBISValueHeaders { get; set; }
    }
}
