//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABA_CH.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOffice
    {
        public EOffice()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public decimal EOfficeID { get; set; }
        public string EOfficeCode { get; set; }
        public string EOfficeDesc { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
