//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABA_CH.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public Error()
        {
            this.MeterErrors = new HashSet<MeterError>();
        }
    
        public decimal ErrorID { get; set; }
        public string ErrorLatinDesc { get; set; }
        public string ErrorFarsiDesc { get; set; }
        public string ErrorArabicDesc { get; set; }
        public decimal OBISID { get; set; }
        public string OBIS { get; set; }
        public Nullable<int> BitNumber { get; set; }
    
        public virtual ICollection<MeterError> MeterErrors { get; set; }
    }
}
