//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABA_CH.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.HashToGroups = new HashSet<HashToGroup>();
        }
    
        public decimal GroupID { get; set; }
        public string GroupName { get; set; }
        public string HashValue { get; set; }
    
        public virtual ICollection<HashToGroup> HashToGroups { get; set; }
    }
}
