//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABA_CH.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public Office()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public decimal OfficeID { get; set; }
        public string OfficeCode { get; set; }
        public string OfficeDesc { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
