//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABA_CH.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitGroup
    {
        public UnitGroup()
        {
            this.OldOBISses = new HashSet<OldOBISs>();
        }
    
        public decimal UnitGroupID { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<OldOBISs> OldOBISses { get; set; }
    }
}
