//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABA_CH.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Credits = new HashSet<Credit>();
            this.OBISValueHeaders = new HashSet<OBISValueHeader>();
            this.Tokens = new HashSet<Token>();
            this.ButtonAccesses = new HashSet<ButtonAccess>();
            this.HashToGroups = new HashSet<HashToGroup>();
            this.UserToGroups = new HashSet<UserToGroup>();
        }
    
        public decimal UserID { get; set; }
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public Nullable<bool> IsVisible { get; set; }
    
        public virtual ICollection<Credit> Credits { get; set; }
        public virtual ICollection<OBISValueHeader> OBISValueHeaders { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
        public virtual ICollection<ButtonAccess> ButtonAccesses { get; set; }
        public virtual ICollection<HashToGroup> HashToGroups { get; set; }
        public virtual ICollection<UserToGroup> UserToGroups { get; set; }
    }
}
