//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABA_CH.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Window
    {
        public Window()
        {
            this.OldOBISses = new HashSet<OldOBISs>();
        }
    
        public int WindowID { get; set; }
        public string windowLatinName { get; set; }
        public string windowFarsiName { get; set; }
        public string windowArabicName { get; set; }
        public Nullable<bool> IsVisable { get; set; }
        public Nullable<decimal> OBIStypeID { get; set; }
    
        public virtual ICollection<OldOBISs> OldOBISses { get; set; }
    }
}
